var treedata = {
   "name":"root",
   "children": [
   {
      "num":0,
      "tab":{
         "active":false,
         "height":0,
         "highlighted":false,
         "id":2473,
         "incognito":false,
         "index":2,
         "openerTabId":2471,
         "pinned":false,
         "selected":true,
         "status":"loading",
         "title":"New Tab",
         "url":"chrome://newtab/",
         "width":0,
         "windowId":2160
      },
      "tabid":2473,
      "fromid":2471,
      "url":"chrome://newtab/",
      "title":"New Tab",
      "removed":false,
      "marked":false,
      "name":"",
      "children":[

      ],
      "___id":"T000002R000002",
      "___s":true
   },
   {
      "num":1,
      "tab":{
         "active":false,
         "height":0,
         "highlighted":false,
         "id":2479,
         "incognito":false,
         "index":2,
         "openerTabId":2471,
         "pinned":false,
         "selected":false,
         "status":"complete",
         "title":"",
         "url":"",
         "width":0,
         "windowId":2160
      },
      "tabid":2479,
      "fromid":2471,
      "url":"",
      "title":"",
      "removed":false,
      "marked":false,
      "name":"",
      "children":[

      ],
      "___id":"T000002R000003",
      "___s":true
   },
   {
      "num":2,
      "tab":{
         "active":false,
         "height":0,
         "highlighted":false,
         "id":2481,
         "incognito":false,
         "index":3,
         "openerTabId":2471,
         "pinned":false,
         "selected":false,
         "status":"complete",
         "title":"",
         "url":"",
         "width":0,
         "windowId":2160
      },
      "tabid":2481,
      "fromid":2471,
      "url":"",
      "title":"",
      "removed":false,
      "marked":false,
      "name":"",
      "children":[
         {
            "num":5,
            "tab":{
               "active":false,
               "height":0,
               "highlighted":false,
               "id":2495,
               "incognito":false,
               "index":4,
               "openerTabId":2481,
               "pinned":false,
               "selected":false,
               "status":"complete",
               "title":"",
               "url":"",
               "width":0,
               "windowId":2160
            },
            "tabid":2495,
            "fromid":2481,
            "url":"",
            "title":"",
            "removed":false,
            "marked":false,
            "name":"",
            "children":[
               {
                  "num":8,
                  "tab":{
                     "active":false,
                     "height":0,
                     "highlighted":false,
                     "id":2507,
                     "incognito":false,
                     "index":5,
                     "openerTabId":2495,
                     "pinned":false,
                     "selected":false,
                     "status":"complete",
                     "title":"",
                     "url":"",
                     "width":0,
                     "windowId":2160
                  },
                  "tabid":2507,
                  "fromid":2495,
                  "url":"",
                  "title":"",
                  "removed":false,
                  "marked":false,
                  "name":"",
                  "children":[

                  ],
                  "___id":"T000002R000010",
                  "___s":true
               },
               {
                  "num":9,
                  "tab":{
                     "active":false,
                     "height":0,
                     "highlighted":false,
                     "id":2509,
                     "incognito":false,
                     "index":6,
                     "openerTabId":2495,
                     "pinned":false,
                     "selected":false,
                     "status":"complete",
                     "title":"",
                     "url":"",
                     "width":0,
                     "windowId":2160
                  },
                  "tabid":2509,
                  "fromid":2495,
                  "url":"",
                  "title":"",
                  "removed":false,
                  "marked":false,
                  "name":"",
                  "children":[

                  ],
                  "___id":"T000002R000011",
                  "___s":true
               }
            ],
            "___id":"T000002R000007",
            "___s":true
         },
         {
            "num":6,
            "tab":{
               "active":false,
               "height":0,
               "highlighted":false,
               "id":2497,
               "incognito":false,
               "index":5,
               "openerTabId":2481,
               "pinned":false,
               "selected":false,
               "status":"complete",
               "title":"",
               "url":"",
               "width":0,
               "windowId":2160
            },
            "tabid":2497,
            "fromid":2481,
            "url":"",
            "title":"",
            "removed":false,
            "marked":false,
            "name":"",
            "children":[
               {
                  "num":10,
                  "tab":{
                     "active":false,
                     "height":0,
                     "highlighted":false,
                     "id":2515,
                     "incognito":false,
                     "index":8,
                     "openerTabId":2497,
                     "pinned":false,
                     "selected":false,
                     "status":"complete",
                     "title":"",
                     "url":"",
                     "width":0,
                     "windowId":2160
                  },
                  "tabid":2515,
                  "fromid":2497,
                  "url":"",
                  "title":"",
                  "removed":false,
                  "marked":false,
                  "name":"",
                  "children":[

                  ],
                  "___id":"T000002R000012",
                  "___s":true
               }
            ],
            "___id":"T000002R000008",
            "___s":true
         },
         {
            "num":7,
            "tab":{
               "active":false,
               "height":0,
               "highlighted":false,
               "id":2503,
               "incognito":false,
               "index":6,
               "openerTabId":2481,
               "pinned":false,
               "selected":false,
               "status":"complete",
               "title":"",
               "url":"",
               "width":0,
               "windowId":2160
            },
            "tabid":2503,
            "fromid":2481,
            "url":"",
            "title":"",
            "removed":false,
            "marked":false,
            "name":"",
            "children":[
               {
                  "num":11,
                  "tab":{
                     "active":false,
                     "height":0,
                     "highlighted":false,
                     "id":2519,
                     "incognito":false,
                     "index":10,
                     "openerTabId":2503,
                     "pinned":false,
                     "selected":false,
                     "status":"complete",
                     "title":"",
                     "url":"",
                     "width":0,
                     "windowId":2160
                  },
                  "tabid":2519,
                  "fromid":2503,
                  "url":"",
                  "title":"",
                  "removed":false,
                  "marked":false,
                  "name":"",
                  "children":[

                  ],
                  "___id":"T000002R000013",
                  "___s":true
               }
            ],
            "___id":"T000002R000009",
            "___s":true
         }
      ],
      "___id":"T000002R000004",
      "___s":true
   },
   {
      "num":3,
      "tab":{
         "active":false,
         "height":0,
         "highlighted":false,
         "id":2483,
         "incognito":false,
         "index":4,
         "openerTabId":2471,
         "pinned":false,
         "selected":false,
         "status":"complete",
         "title":"",
         "url":"",
         "width":0,
         "windowId":2160
      },
      "tabid":2483,
      "fromid":2471,
      "url":"",
      "title":"",
      "removed":false,
      "marked":false,
      "name":"",
      "children":[
         {
            "num":12,
            "tab":{
               "active":false,
               "height":0,
               "highlighted":false,
               "id":2523,
               "incognito":false,
               "index":12,
               "openerTabId":2483,
               "pinned":false,
               "selected":false,
               "status":"complete",
               "title":"",
               "url":"",
               "width":0,
               "windowId":2160
            },
            "tabid":2523,
            "fromid":2483,
            "url":"",
            "title":"",
            "removed":false,
            "marked":false,
            "name":"",
            "children":[

            ],
            "___id":"T000002R000014",
            "___s":true
         },
         {
            "num":13,
            "tab":{
               "active":false,
               "height":0,
               "highlighted":false,
               "id":2525,
               "incognito":false,
               "index":13,
               "openerTabId":2483,
               "pinned":false,
               "selected":false,
               "status":"complete",
               "title":"",
               "url":"",
               "width":0,
               "windowId":2160
            },
            "tabid":2525,
            "fromid":2483,
            "url":"",
            "title":"",
            "removed":false,
            "marked":false,
            "name":"",
            "children":[

            ],
            "___id":"T000002R000015",
            "___s":true
         },
         {
            "num":14,
            "tab":{
               "active":false,
               "height":0,
               "highlighted":false,
               "id":2527,
               "incognito":false,
               "index":14,
               "openerTabId":2483,
               "pinned":false,
               "selected":false,
               "status":"complete",
               "title":"",
               "url":"",
               "width":0,
               "windowId":2160
            },
            "tabid":2527,
            "fromid":2483,
            "url":"",
            "title":"",
            "removed":false,
            "marked":false,
            "name":"",
            "children":[

            ],
            "___id":"T000002R000016",
            "___s":true
         },
         {
            "num":15,
            "tab":{
               "active":false,
               "height":0,
               "highlighted":false,
               "id":2529,
               "incognito":false,
               "index":15,
               "openerTabId":2483,
               "pinned":false,
               "selected":false,
               "status":"complete",
               "title":"",
               "url":"",
               "width":0,
               "windowId":2160
            },
            "tabid":2529,
            "fromid":2483,
            "url":"",
            "title":"",
            "removed":false,
            "marked":false,
            "name":"",
            "children":[

            ],
            "___id":"T000002R000017",
            "___s":true
         }
      ],
      "___id":"T000002R000005",
      "___s":true
   },
   {
      "num":4,
      "tab":{
         "active":false,
         "height":0,
         "highlighted":false,
         "id":2491,
         "incognito":false,
         "index":5,
         "openerTabId":2471,
         "pinned":false,
         "selected":false,
         "status":"complete",
         "title":"",
         "url":"",
         "width":0,
         "windowId":2160
      },
      "tabid":2491,
      "fromid":2471,
      "url":"",
      "title":"",
      "removed":false,
      "marked":false,
      "name":"",
      "children":[
         {
            "num":16,
            "tab":{
               "active":false,
               "height":0,
               "highlighted":false,
               "id":2539,
               "incognito":false,
               "index":17,
               "openerTabId":2491,
               "pinned":false,
               "selected":false,
               "status":"complete",
               "title":"",
               "url":"",
               "width":0,
               "windowId":2160
            },
            "tabid":2539,
            "fromid":2491,
            "url":"",
            "title":"",
            "removed":false,
            "marked":false,
            "name":"",
            "children":[

            ],
            "___id":"T000002R000018",
            "___s":true
         },
         {
            "num":17,
            "tab":{
               "active":false,
               "height":0,
               "highlighted":false,
               "id":2541,
               "incognito":false,
               "index":18,
               "openerTabId":2491,
               "pinned":false,
               "selected":false,
               "status":"complete",
               "title":"",
               "url":"",
               "width":0,
               "windowId":2160
            },
            "tabid":2541,
            "fromid":2491,
            "url":"",
            "title":"",
            "removed":false,
            "marked":false,
            "name":"",
            "children":[

            ],
            "___id":"T000002R000019",
            "___s":true
         }
      ],
      "___id":"T000002R000006",
      "___s":true
   }]
};

var tree = d3.layout.tree()
   .sort(null)
   .size([size.height, size.width - maxLabelLength*options.fontSize])
   .children( function(d) {
      return (!d.children || d.children.length === 0) ? null : d.children;
   });

var nodes = tree.nodes(treeData);
var links = tree.links(nodes);

